const PRODUITS=[],CATEGORIES=[],SUJETS={},GUIDES={},BIENTOT=new Set();
const LENSES=[['Les faits','Qu’est-ce qui s’est réellement passé?','Décris les événements observables. Essaie de distinguer les faits de ton interprétation.'],['Mon ressenti','Comment est-ce que je me sens?','Prends un moment pour nommer ton émotion, ton inconfort ou ton sentiment de sécurité.'],['La répétition','Est-ce isolé ou récurrent?','Observe la fréquence et les changements dans le temps, sans tirer un verdict d’un seul élément.'],['Le changement chez moi','Est-ce que je me modifie pour éviter quelque chose?','Observe ce que tu n’oses plus dire, ce que tu évites et les adaptations que tu fais.'],['Ma liberté d’être moi','Puis-je encore être pleinement moi?','Réfléchis à la place de tes choix, de ton identité et de ton autonomie dans cette situation.'],['Ma possibilité de parler','Puis-je parler, dire non, exprimer un besoin ou demander de l’aide?','Observe si tu peux exprimer tes besoins et trouver du soutien. Tu peux choisir une prochaine étape à ton rythme.']];
function showLens(i){const lens=LENSES[i];document.querySelector('#lens-label').textContent=lens[0].toUpperCase();document.querySelector('#lens-question').textContent=lens[1];document.querySelector('#lens-description').textContent=lens[2];document.querySelectorAll('[data-lens]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.lens)===i)));}
document.querySelectorAll('[data-lens]').forEach(b=>b.addEventListener('click',()=>showLens(Number(b.dataset.lens))));
document.querySelectorAll('[data-open-lens]').forEach(a=>a.addEventListener('click',()=>showLens(Number(a.dataset.openLens))));
const menu=document.querySelector('#menu'),nav=document.querySelector('#navigation');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}});
const normalized=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();document.querySelector('#search').addEventListener('input',e=>{const query=normalized(e.target.value.trim());let visible=0;document.querySelectorAll('[data-topic]').forEach(a=>{a.hidden=!normalized(a.dataset.topic+' '+a.textContent).includes(query);if(!a.hidden)visible++});document.querySelector('#empty').hidden=visible>0});
document.querySelector('.print-lenses').innerHTML=LENSES.map(l=>`<article><h3>${l[0]} — ${l[1]}</h3><p>${l[2]}</p></article>`).join('');document.querySelector('#print').addEventListener('click',()=>window.print());
document.querySelectorAll('[data-request]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#interest').value=a.dataset.request}));
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const interest=document.querySelector('#interest').value;window.location.href=`mailto:info@lesconstructionslapointe.com?subject=${encodeURIComponent(interest)}`;document.querySelector('#contact-status').textContent='Termine ta demande dans ton application courriel. Si elle ne s’ouvre pas, utilise l’adresse affichée.'});
