import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id bigint,bucket_id text);alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');`);
await db.exec(await readFile(new URL('../backend/setup.sql',import.meta.url),'utf8'));
await db.exec(`insert into public.ra_roles values('00000000-0000-0000-0000-000000000001','admin'),('00000000-0000-0000-0000-000000000002','content_manager');`);
const state={texts:[{id:'0',label:'Page',value:'Bonjour'}],images:[],products:[],categories:[],articles:[]};
let checks=0;
async function as(role,user){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${user||''}',false);set role ${role};`);}
async function deny(sql,args=[]){await assert.rejects(db.query(sql,args));checks++;}
await as('anon');await deny('select public.ra_write($1,$2,0,null)',['save',JSON.stringify(state)]);
await deny('select * from public.ra_draft');
await as('authenticated','00000000-0000-0000-0000-000000000003');
await deny('select public.ra_write($1,$2,0,null)',['save',JSON.stringify(state)]);
assert.equal((await db.query('select * from public.ra_draft')).rows.length,0);checks++;
await as('authenticated','00000000-0000-0000-0000-000000000002');
await deny(`update public.ra_roles set role='admin'`);
await deny(`insert into public.ra_live values(1,'{}')`);
await deny(`delete from public.ra_history`);
await deny(`alter table public.ra_draft add column stolen text`);
await deny(`drop table public.ra_draft`);
assert.equal((await db.query('select public.ra_write($1,$2,0,null)',['save',JSON.stringify(state)])).rows[0].ra_write,1);checks++;
assert.equal((await db.query('select * from public.ra_live')).rows.length,0);checks++;
await deny('select public.ra_write($1,$2,0,null)',['save',JSON.stringify(state)]);
await deny('select public.ra_write($1,null,1,1)',['restore']);
await deny('select public.ra_write($1,$2,1,null)',['save',JSON.stringify({...state,keys:'secret'})]);
await deny('select public.ra_write($1,$2,1,null)',['save',JSON.stringify({...state,products:[{id:"bad');alert(1)//",cat:'test',prix:1}]})]);
await deny('select public.ra_write($1,$2,1,null)',['save',JSON.stringify({...state,images:[{id:'0',src:'javascript:alert(1)',alt:''}]})]);
await deny('select public.ra_write($1,$2,1,null)',['save',JSON.stringify({...state,products:[{id:'good',cat:'test',prix:-1}]})]);
assert.equal((await db.query('select public.ra_write($1,null,1,null)',['publish'])).rows[0].ra_write,2);checks++;
assert.equal((await db.query('select * from public.ra_history')).rows.length,0);checks++;
await as('anon');assert.deepEqual((await db.query('select content from public.ra_live')).rows[0].content,state);checks++;
await as('authenticated','00000000-0000-0000-0000-000000000001');
const history=(await db.query('select * from public.ra_history order by id')).rows;
assert.equal(history.length,3);checks++;
assert.equal((await db.query('select public.ra_write($1,null,2,$2)',['restore',history[0].id])).rows[0].ra_write,3);checks++;
assert.deepEqual((await db.query('select content from public.ra_live')).rows[0].content,state);checks++;
await db.exec('reset role');
await db.exec(`delete from public.ra_roles where user_id='00000000-0000-0000-0000-000000000002'`);
await as('authenticated','00000000-0000-0000-0000-000000000002');
await deny('select public.ra_write($1,$2,3,null)',['save',JSON.stringify(state)]);
console.log(`${checks} permission and transaction checks passed`);await db.close();
